config/routes.rb
Beauty::Application.routes.draw do
  resources :graph_employee_statuses

  resources :employee_sanction_workings

  resources :graph_employee_status_by_bands

  resources :graph_hospital_vacants

  resources :posting_types

  resources :vw_sanctioned_working_by_hospitals

  resources :employee_cadres

  resources :graph_hospital_vacant_by_bands

  resources :employee_age_by_bands

  resources :emp_tenure_by_bands

  resources :hospital_types

  resources :sanctioned_by_designations

  resources :recruitment_modes

  resources :employee_work_details

  resources :reports

  resources :emp_spec_views

  resources :emp_gen_views

  resources :emp_qual_views

  resources :relationships

  resources :addresses

  resources :additional_charges

  resources :sanctioned_posts

  resources :health_dept_locations

  resources :blocks

  resources :divisions

  resources :employment_types

  resources :hospital_reports

  resources :roles

  resources :user

  resources :hospitals

  devise_for :users
  devise_for :users do 
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit' => 'devise/registrations#edit' 
    get '/users/new'  => 'devise/registrations#new'
  end

  resources :promotions

  resources :showcauses

  resources :achievements

  resources :leaveemps

  resources :leave_types

  resources :qualifications

  resources :universities

  resources :specialisations

  resources :qualification_names

  resources :qualification_types

  resources :dependents

  resources :statuses

  resources :relations

  resources :postings

  resources :designations

  resources :institution_masters

  resources :institution_types

  resources :special_cadres

  resources :tempus

  resources :locations

  resources :religions

  resources :categories

  resources :castes

  resources :martial_stats

  resources :blood_groups

  resources :genders

  resources :pincodes

  resources :states

  resources :cities

  resources :districts

  resources :taluks

  resources :emp_edus

  resources :emp_adds

  resources :employees

  resources :posts

  get "home/index"

  root :to => 'home#index'

end

app/models/block.rb
class Block < ActiveRecord::Base
  attr_accessible :block_name, :district_id

  has_many:health_dept_locations
  belongs_to:district
  belongs_to:location
  has_many:locations 
  has_many:hospitals
  has_many:sanctioned_posts

  validates_associated :district
  has_many:employees

end

app/models/district.rb
class District < ActiveRecord::Base
  attr_accessible :district_name, :division_id

  has_many:postings
  has_many:institution_masters
  has_many:health_dept_locations
  has_many:blocks  
  belongs_to:division
  has_many:sanctioned_post

  validates_associated :blocks, :division

  has_many:employees
end

app/models/division.rb
class Division < ActiveRecord::Base
  attr_accessible :division_name, :state_id

  has_many:health_dept_locations
  belongs_to:state
  has_many:districts
  has_many:hospitals

  has_many:sanctioned_posts

  validates_associated :districts
  has_many:employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :blood_group_id, :caste_id, :category_id, :emp_dob, :emp_email, :emp_fathername, :emp_fname, :emp_full_name, :gender_id, :emp_id, :emp_lname, :emp_loc_master_id, :emp_mname, :emp_mobile_no, :emp_permanent_address, :emp_phone_no, :religion_id, :employee_cadre_id, :ddo_code, :employment_type_id, :district_id, :division_id, :hospital_id, :block_id
  
  has_many:postings
  has_many:dependents
  has_many:qualifications
  has_many:leaveemps
  has_many:achievements
  has_many:showcauses
  has_many:promotions
  has_many:additional_charges
  has_many:addresses
  has_many:employee_work_details
  has_many:employee_sanction_workings
  
  belongs_to:gender
  belongs_to:category
  belongs_to:religion
  belongs_to:caste
  belongs_to:blood_group
  belongs_to:employee_cadre 
  belongs_to:employment_type
  belongs_to:hospital
  belongs_to:district
  belongs_to:division
  belongs_to:block
end

app/models/employee_sanction_working.rb
class EmployeeSanctionWorking < ActiveRecord::Base
	self.table_name = 'employee_sanction_working'
	belongs_to:hospital
	belongs_to:employee
end

app/models/employment_type.rb
class EmploymentType < ActiveRecord::Base
  attr_accessible :employment_type
  has_many:employees
end

app/models/graph_employee_status.rb
class GraphEmployeeStatus < ActiveRecord::Base
  self.table_name = 'graph_employee_status'

  has_many:graph_employee_status_by_bands
end

app/models/graph_employee_status_by_band.rb
class GraphEmployeeStatusByBand < ActiveRecord::Base
  self.table_name = 'graph_employee_status_by_band'

  belongs_to:graph_employee_status
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  attr_accessible  :beds, :fax_no, :hospital_name, :phone_no, :district_id, :institution_type_id, :location_id, :division_id, :block_id, :hospital_type_id, :IsAdministrativeLocation, :IsTribal, :latitude, :longitude

  belongs_to :district
  belongs_to :division
  belongs_to :institution_type  
  belongs_to :hospital_type
  belongs_to :block

  has_many :hospital_reports
  has_many:health_dept_locations
  has_many:sanctioned_posts
  has_many:postings
  has_many:vw_sanctioned_working_by_hospitals
  has_many:employee_sanction_workings  
  has_many:employees

  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |hospital|
      csv << hospital.attributes.values_at(*column_names)
    end
  end
end
end

app/models/sanctioned_post.rb
class SanctionedPost < ActiveRecord::Base
  attr_accessible :hospital_id, :sanctioned_posts, :designation_id, :district_id, :division_id, :block_id
  belongs_to:designation
  belongs_to:hospital
  belongs_to:district
  belongs_to:division
  belongs_to:block
  
end

app/controllers/employee_sanction_workings_controller.rb
class EmployeeSanctionWorkingsController < InheritedResources::Base
end

app/controllers/graph_employee_status_by_bands_controller.rb
class GraphEmployeeStatusByBandsController < InheritedResources::Base


def index
  @q = GraphEmployeeStatusByBand.search(params[:q])
  @graph_employee_status_by_bands = @q.result(:distinct => true)
end

end

app/controllers/graph_employee_statuses_controller.rb
class GraphEmployeeStatusesController < InheritedResources::Base
end

app/helpers/employee_sanction_workings_helper.rb
module EmployeeSanctionWorkingsHelper
end

app/helpers/graph_employee_status_by_bands_helper.rb
module GraphEmployeeStatusByBandsHelper
end

app/helpers/graph_employee_statuses_helper.rb
module GraphEmployeeStatusesHelper
end

app/views/emp_gen_views/index.html.erb
<link rel="stylesheet" href="//cdn.oesmith.co.uk/morris-0.4.1.min.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdn.oesmith.co.uk/morris-0.4.1.min.js"></script>


<h1>Doctors by Gender</h1>
<br><br>


<div class="row">
<div class="span4">
<table class="table table-bordered">
  <thead>
    <tr>
        <th>Gender</th>
        <th>Number of Employees</th>
    </tr>
  </thead>
<tbody id="emp_gen_views">
<% @emp_gen_views.each do |emp_gen_view| %>
  <tr>
        <td><%= emp_gen_view.gender %></td>
        <td><%= emp_gen_view.number_of_employees %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>
	<div class="span8">
		<%= content_tag :div, "", id: "gen_chart" %>
	</div>

</div>

<script>

var data = [];
 
$('tbody#emp_gen_views tr').each(function(){
  var row = {
    value: parseInt($(this).children('td:last').text()),
    label: $(this).children('td:first').text()
  };
 
  data.push(row);
});
 

Morris.Donut({
  element: 'gen_chart',
  data: data
});
</script>

app/views/emp_qual_views/index.html.erb
<link rel="stylesheet" href="//cdn.oesmith.co.uk/morris-0.4.1.min.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdn.oesmith.co.uk/morris-0.4.1.min.js"></script>


<h1>Doctors by Qualification</h1>
<br><br>

<div class="row">
<div class="span4">
<table class="table table-bordered">
  <thead>
    <tr>
	<th>Qualification Name</th>	
	<th>Number of Employees</th>
    </tr>
  </thead>
<tbody id="emp_qual_views">
<% @emp_qual_views.each do |emp_qual_view| %>
  <tr>
	<td><%= emp_qual_view.qualification_name %></td>
	<td><%= emp_qual_view.number_of_employees %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>
	<div class="span8">
		<%= content_tag :div, "", id: "qual_chart" %>
	</div>

</div>

<script>
var data = [];
 
$('tbody#emp_qual_views tr').each(function(){
  var row = {
    value: parseInt($(this).children('td:last').text()),
    label: $(this).children('td:first').text()
  };
 
  data.push(row);
});
 

Morris.Donut({
  element: 'qual_chart',
  data: data
});
 
</script>

app/views/employee_sanction_workings/_form.html.erb
<%= semantic_form_for @employee_sanction_working do |f| %>
  <%= f.inputs do %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/employee_sanction_workings/edit.html.erb
<h1>Editing employee_sanction_working</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee_sanction_working %> |
<%= link_to 'Back', employee_sanction_workings_path %>

app/views/employee_sanction_workings/index.html.erb
<h1>Listing employee_sanction_workings</h1>

<table>
  <tr>
      
      <th>Working Since</th>
      <th>Employment Type</th>
      <th>Employee Class</th>
      <th>Specialisation</th>
      <th>Qualification</th>
      <th>Designation (English)</th>
      <th>Designation (Hindi)</th>
      <th>Working Status</th>
  </tr>

<% @employee_sanction_workings.each do |employee_sanction_working| %>
  <tr>
    
    <td><%= employee_sanction_working.try(:join_date).try(:strftime, "%d-%m-%Y") || "Not Entered" %></td>
    <td><%= employee_sanction_working.employment_type%></td>
    <td><%= employee_sanction_working.employee_class%></td>
    <td><%= employee_sanction_working.specialisation_name%></td>
    <td><%= employee_sanction_working.qualification_name%></td>
    <td><%= employee_sanction_working.Designation_English%></td>
    <td><%= employee_sanction_working.Designation_hindi%></td>
    <td><%= employee_sanction_working.status_name%></td>
  </tr>
<% end %>
</table>

app/views/employee_sanction_workings/new.html.erb
<h1>New employee_sanction_working</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_sanction_workings_path %>

app/views/employee_sanction_workings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_employee_sanction_working_path(@employee_sanction_working) %> |
<%= link_to 'Back', employee_sanction_workings_path %>

app/views/employees/_form.html.erb
<%= simple_form_for @employee, :validate => true, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :emp_id, label: 'Employee ID'%>
  <%= f.input :emp_full_name, label: "Employee's Full Name"%>
  <%= f.association :employee_cadre,label_method: :employee_cadre_type, value_method: :id, include_blank: false%>
  <%= f.association :employment_type,label_method: :employment_type, value_method: :id, include_blank: false%>
  <%= f.input :emp_fname, label: 'First Name'%>
  <%= f.input :emp_mname, label: 'Middle Name'%>
  <%= f.input :emp_lname, label: 'Last Name'%>
  <%= f.input :emp_fathername, label: :"Father's Name" %>

  <%= f.association :gender,label_method: :gender_name, value_method: :id, include_blank: false %>
  <%= f.input :emp_dob,as: :string%>
  <%= f.association :category,label_method: :category_name, value_method: :id, include_blank: false %>
  <%= f.association :religion,label_method: :religion_name, value_method: :id, include_blank: false %>
  <%= f.association :caste,label_method: :caste_name, value_method: :id, include_blank: false %>
  <%= f.association :blood_group,label_method: :blood_group_type, value_method: :id, include_blank: false %>

  <%= f.input :emp_permanent_address %>
  <%= f.input :emp_loc_master_id %>
  <%= f.association :division,label_method: :division_name, value_method: :id, include_blank: false%>

  <%= f.input :district_id do %>
      <%= f.grouped_collection_select :district_id, Division.order(:division_name), :districts, :division_name, :id, :district_name, include_blank: true, label: 'District'  %>
  <% end %>

  <%= f.input :block_id do %>
      <%= f.grouped_collection_select :block_id, District.order(:district_name), :blocks, :district_name, :id, :block_name, include_blank: true, label: 'Block' %>
  <% end %>

  <%= f.input :hospital_id do %>
      <%= f.grouped_collection_select :hospital_id, Block.order(:block_name), :hospitals, :block_name, :id, :hospital_name, include_blank: true, label: 'Hospital' %>
  <% end %>
  <%= f.input :emp_phone_no %>
  <%= f.input :emp_mobile_no %>
  <%= f.input :emp_email %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employees_path, :class => 'btn' %>              
  </div>
<% end %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-bordered" id="employe">
  <thead>
    <tr>
      <th>Employee ID</th>
      <th>Treasury ID</th>
      <th>Employee Full Name</th>
      <th>Current Posting</th>
      <th>Employee Qualifications</th>
      <th>Employment Type</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.emp_id %></td>
        <td><%= employee.emp_treasury_id %></td>
        <td><%= link_to employee.emp_full_name,employee_path(employee) %></td>
	<td><%= employee.postings.last.try(:hospital).try(:hospital_name) || "N/A" %></td>
	<td><%= employee.qualifications.collect{|u| u.qualification_name.Qualification_name}.join(', ') %></td>
        <td><%= employee.try(:employment_type).try(:employment_type) || "N/A" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_employee_path,
            :class => 'btn' %>
<script>
    $(document).ready(function() {
      $('#employe').dataTable( {
        "sPaginationType": "bootstrap"
      } );
    }
  );
</script>

app/views/graph_employee_status_by_bands/_form.html.erb
<%= semantic_form_for @graph_employee_status_by_band do |f| %>
  <%= f.inputs do %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/graph_employee_status_by_bands/edit.html.erb
<h1>Editing graph_employee_status_by_band</h1>

<%= render 'form' %>

<%= link_to 'Show', @graph_employee_status_by_band %> |
<%= link_to 'Back', graph_employee_status_by_bands_path %>

app/views/graph_employee_status_by_bands/new.html.erb
<h1>New graph_employee_status_by_band</h1>

<%= render 'form' %>

<%= link_to 'Back', graph_employee_status_by_bands_path %>

app/views/graph_employee_status_by_bands/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_graph_employee_status_by_band_path(@graph_employee_status_by_band) %> |
<%= link_to 'Back', graph_employee_status_by_bands_path %>

app/views/graph_employee_statuses/_form.html.erb
<%= semantic_form_for @graph_employee_status do |f| %>
  <%= f.inputs do %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/graph_employee_statuses/edit.html.erb
<h1>Editing graph_employee_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @graph_employee_status %> |
<%= link_to 'Back', graph_employee_statuses_path %>

app/views/graph_employee_statuses/index.html.erb
<h1>Listing graph_employee_statuses</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @graph_employee_statuses.each do |graph_employee_status| %>
  <tr>
    <td><%= link_to 'Show', graph_employee_status %></td>
    <td><%= link_to 'Edit', edit_graph_employee_status_path(graph_employee_status) %></td>
    <td><%= link_to 'Destroy', graph_employee_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Graph employee status', new_graph_employee_status_path %>

app/views/graph_employee_statuses/new.html.erb
<h1>New graph_employee_status</h1>

<%= render 'form' %>

<%= link_to 'Back', graph_employee_statuses_path %>

app/views/graph_employee_statuses/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_graph_employee_status_path(@graph_employee_status) %> |
<%= link_to 'Back', graph_employee_statuses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HRMIS - Bhopal</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<% if user_signed_in? %>
<body>


    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <p class="navbar-text pull-right">
            Logged in as:
            <a href="/users/edit" data-method="get"><%= current_user.fname %> <%= current_user.lname %></a>
            <% if current_user.role.role_name == 'admin' %>
            |
            <a href="/user" data-method="get">Manage User</a>
            <% end %>
            |
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          </p>
          <a class="brand" href="/home/index">HRMIS</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
            <!-- <li><%= link_to "HRMIS Patients", posts_path %></li> -->
<% if current_user.email == "demo@venkatmangudi.com" %>
              <li class="dropdown">
                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Employees <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                     <li><%= link_to "View Employees", employees_path %></li>
                          <li><a href="/employees/new" data-method="get">Add Employee</a></li>
                    <li class="divider"></li>
                   <!--  <li><a tabindex="-1" href="#">Separated link</a></li> -->
                  </ul>
              </li>

<% else %>
<li class="dropdown">
                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Dashboard <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
			                      <li class="dropdown-submenu">
                        <a tabindex="-1" href="#">Reports</a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Doctors by Specialisation", emp_spec_views_path %></li>
                          <li><%= link_to "Doctors by Qualification", emp_qual_views_path %></li>
                          <li><%= link_to "Doctors by Gender", emp_gen_views_path %></li>
			  <li class="divider"></li>
			  <li><%= link_to "Sanctioned By Designations", sanctioned_by_designations_path %></li>
			  <li class="divider"></li>
		          <li><%= link_to "Employees by Age Band", employee_age_by_bands_path %></li>
			  <li><%= link_to "Employees by Tenure Band", emp_tenure_by_bands_path %></li>
			  <li class="divider"></li>
			  <li><%= link_to "Hospital Vacant By Band", graph_hospital_vacant_by_bands_path %></li>
			  <li><%= link_to "Employee Status By Band", graph_employee_status_by_bands_path %></li>
                        </ul>
                      </li>
                  <!--        <li><%= link_to "Report Name1", employees_path %></li>
                          <li><%= link_to "Report Name2", qualifications_path %></li>
                          <li><%= link_to "Report Name3", specialisations_path %></li>
                          <li><%= link_to "Report Name4", dependents_path %></li> -->

                    <!-- <li class="divider"></li>
                    <li><a tabindex="-1" href="#">Separated link</a></li> -->
                  </ul>
</li>
<li class="dropdown">
                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Employees <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                    <li class="dropdown-submenu">
                        <a tabindex="-1" href="#">Doctors</a>
                        <ul class="dropdown-menu">
                           <li><%= link_to "View Doctors", employees_path %></li>
                           <li><a href="/employees/new" data-method="get">Add Doctor</a></li>
                        </ul>
                    </li>
                 <!--   <li class="dropdown-submenu">
                        <a tabindex="-1" href="#">Nurses</a>
                        <ul class="dropdown-menu">
                           <li><%= link_to "View Employees", employees_path %></li>
                           <li><a href="/employees/new" data-method="get">Add Employee</a></li>
                        </ul>
                    </li>
                    <li class="dropdown-submenu">
                        <a tabindex="-1" href="#">Para Medical Staff</a>
                        <ul class="dropdown-menu">
                           <li><%= link_to "View Employees", employees_path %></li>
                           <li><a href="/employees/new" data-method="get">Add Employee</a></li>
                        </ul>
                    </li>
                    <li class="dropdown-submenu">
                        <a tabindex="-1" href="#">Clerical Staff</a>
                        <ul class="dropdown-menu">
                           <li><%= link_to "View Employees", employees_path %></li>
                           <li><a href="/employees/new" data-method="get">Add Employee</a></li>
                        </ul>
                    </li>
                    <li class="dropdown-submenu">
                        <a tabindex="-1" href="#">Non-Clerical Staff</a>
                        <ul class="dropdown-menu">
                           <li><%= link_to "View Employees", employees_path %></li>
                           <li><a href="/employees/new" data-method="get">Add Employee</a></li>
                        </ul>
                    </li>    --> 
			<li class="divider"></li>
			<li><%= link_to "Employee Cadre", employee_cadres_path %></li>
			<li><%= link_to "Admin Office", employees_path %></li>
			<li class="divider"></li>
			<li><%= link_to "Blood Groups", blood_groups_path %></li>
			<li><%= link_to "Marital Status", martial_stats_path %></li>
			<li><%= link_to "Religions", religions_path %></li>
			<li><%= link_to "Castes", castes_path %></li>
                    <!-- <li class="divider"></li>
                    <li><a tabindex="-1" href="#">Separated link</a></li> -->
                  </ul>
              </li>



              <li class="dropdown">
                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Hierarchies <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                    <li><%= link_to "States", states_path %></li>
                    <li><%= link_to "Divisions", divisions_path %></li>
                    <li><%= link_to "Districts", districts_path %></li>
                    <li><%= link_to "Blocks", blocks_path %></li>



<!--                    <li><%= link_to "Healthcare Centers", hospitals_path %></li>
                    <li class="divider"></li>


                      <li class="dropdown-submenu">
                        <a tabindex="-1" href="#">Institutions</a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Institutions Master", institution_masters_path %></li>
                          <li class="divider"></li>                          
                          <li><%= link_to "Institution Type", institution_types_path %></li>
                          <li><%= link_to "Special Cadre", special_cadres_path %></li>
                        </ul>
                      </li>                    
                    
                    <li class="divider"></li>
                      <li><%= link_to "Gender", genders_path %></li>
                      <li><%= link_to "Marial Status", martial_stats_path %></li>
                      <li><%= link_to "Blood Group", blood_groups_path %></li>
                                        
                     <li class="divider"></li>
                      <li class="dropdown-submenu">
                        <a tabindex="-1" href="#">Ethnicity</a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Caste", castes_path %></li>
                          <li><%= link_to "Category", categories_path %></li>
                          <li><%= link_to "Religion", religions_path %></li>
                        </ul>
                      </li>

                    <li class="divider"></li>
                      <li class="dropdown-submenu">
                        <a tabindex="-1" href="#">Location Data</a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Location Master", locations_path %></li>
                          <li class="divider"></li>
                          <li><%= link_to "Districts", districts_path %></li>
                          <li><%= link_to "Cities", cities_path %></li>
                          <li><%= link_to "States", states_path %></li>
                          <li><%= link_to "Pincodes", pincodes_path %></li>
                        </ul>
                      </li>    -->
<% end %>
                    <!-- <li class="divider"></li>
                    <li><a tabindex="-1" href="#">Separated link</a></li> -->
                  </ul>
              </li>




	       <li class="dropdown">
                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Hospitals <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                   	<li><%= link_to "Hospital List", hospitals_path %></li>
	                <li><%= link_to "Sanctioned Posts", sanctioned_posts_path %></li>
                        <li><%= link_to "Additional Charges", additional_charges_path %></li>
		   </ul>
		  </li>



            <!-- <li><%= link_to "Venkat Sir" %></li>    -->         
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<% end %>
<div class="container">
	<div class="row">
    <%= render partial: "layouts/flash_messages", locals: { flash: flash }%>
		<div class="span12"><%= yield %></div>
<!-- 		<div class="span3">
			<h2>About Us</h2>
			This is SkyKOG Magic :) 

		</div> -->
	</div>
</div>
</body>
</html>